[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_based = "5eMepu4HKkhKsBX7tkSKSRsHAekV83oy5tca2TzVktXz"

[programs.devnet]
asset_based = "5eMepu4HKkhKsBX7tkSKSRsHAekV83oy5tca2TzVktXz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_wrapper = "yarn run ts-node scripts/init_wrapper.ts "
