[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_based = "497QUkPeKAXrqDQzGGb73P9dfY5C76ZmsXibT2dP8mcu"

[programs.devnet]
asset_based = "497QUkPeKAXrqDQzGGb73P9dfY5C76ZmsXibT2dP8mcu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_wrapper = "yarn run ts-node scripts/init_wrapper.ts"
init_mint = "yarn run ts-node scripts/dev-tokens.ts"
init_token_account = "yarn run ts-node scripts/dev-create-spl-tokens.ts"
airdrop_sol = "yarn run ts-node scripts/dev-airdrop-sol.ts"
airdrop_tokens = "yarn run ts-node scripts/dev-airdrop-tokens.ts"
