[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
handmade_naive = "Dq1SdmsJ5GpeGazTRbhFVoQkowZDY77CDdVhcoAw5Zu"

[programs.devnet]
handmade_naive = "Dq1SdmsJ5GpeGazTRbhFVoQkowZDY77CDdVhcoAw5Zu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
