[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_based = "GWceSREg4H34gWhTXy3sY9KeRgcviAz8FFSmWaoooGop"

[programs.devnet]
asset_based = "GWceSREg4H34gWhTXy3sY9KeRgcviAz8FFSmWaoooGop"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_wrapper = "yarn run ts-node scripts/init_wrapper.ts"
init_mint = "yarn run ts-node scripts/init_mint.ts"
init_token_account = "yarn run ts-node scripts/dev-create-spl-tokens.ts"
airdrop_wrapped_sol = "yarn run ts-node scripts/dev-airdrop-wrapped-sol.ts"
airdrop_sol = "yarn run ts-node scripts/dev-airdrop-sol.ts"
airdrop_tokens = "yarn run ts-node scripts/dev-airdrop-tokens.ts"
get_address_from_pseudo = "yarn run ts-node scripts/get_address_from_pseudo.ts"
